<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTinyUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tinyurl');
        $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('hash', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('url', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    }

}