<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/07/17 14:21:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tinyurl',
  'username' => 'root',
  'password' => 'kokkai3',
  'name' => 'doctrine',
)),);
